Repository Seneca-PlaNA/body-contouring-clinic, pull requests merged in 2021-01, with the labels that each got.

#1 01/20 React + Express merging record
  README.md
  body-contouring-clinic/.eslintcache
  body-contouring-clinic/package-lock.json
  body-contouring-clinic/package.json
  body-contouring-clinic/servers/server.js
  body-contouring-clinic/src/App.js
Labels: documentation, enhancement

#19 Fix #18: Created SideBar to use it globally
  src/App.css
  src/App.js
  src/Request/ListAllRequest.js
  src/Request/Request.css
  src/Request/RequestHome.js
  src/Request/index.js
  src/SideBar/SideBar.js
  src/resources/searchIcon.png
Labels: enhancement, front-end

#35 Appointment basic UI
  src/App.css
  src/Appointment/Appointment.js
  src/Appointment/AppointmentHome.js
  src/Appointment/Appointments.js
  src/Appointment/CreateAppointment.js
  src/RouterConfig.js
Labels: front-end, priority: high
