Repository Seneca-PlaNA/body-contouring-clinic, pull requests merged in 2021-04, with the labels that each got.

#359 Remove duplicate dates from appointment creation selection
  servers/handlers/dateHandler.js
  servers/server.js
  src/Appointment/Admin/CreateAppointmentAdminbyStaff.js
  src/Appointment/CreateAppointmentbyStaff.js
Labels: bug

#364 Date and time validation for create and edit schedule
  src/StaffSchedule/CreateSchedule.js
  src/StaffSchedule/EditStaffSchedule.js
Labels: bug

#365 Don't show booked schedule on creating appointment
  models/workSchedule.js
  src/Appointment/Admin/CreateAppointmentAdminbyStaff.js
  src/Appointment/CreateAppointmentbyStaff.js
Labels: bug

#371 Add status and status search to schedule list
  src/StaffSchedule/ViewSchedulesList.js
Labels: enhancement

#374 Add validation for terms and condition checkbox
  src/Register/TermsAndConditions.js
Labels: bug

#376 Add balance validation, and modify balance page
  src/Customer/Admin/CustomerBalanceDetailAdmin.js
Labels: enhancement

#378 Staff can add notes to customer
  models/account.js
  src/Customer/Admin/CustomerProfileAdmin.js
Labels: bug, enhancement

#382 Issue 339: Validation for create/edit request and lastUpdateTime fixed
  src/Request/CreateRequest.js
  src/Request/EditRequest.js
Labels: bug

#383 Issue 344: File extension validation
  src/Request/CreateRequest.js
  src/Request/EditRequest.js
  src/VIP/Admin/CreateOffer.js
  src/VIP/Admin/EditOffer.js
Labels: bug

#349 Issue337 - Fixed reset issue
  src/Appointment/Admin/AppointmentsAdmin.js
  src/Request/Admin/RequestHomebyAdmin.js
  src/Request/RequestHome.js
Labels: bug

#387 Added find password
  servers/server.js
  src/Register/ChangePassword.js
  src/Register/Forgot_Password.js
  src/Register/Login.js
  src/RouterConfig.js
Labels: enhancement

#391 Sort balance by date (newlest first)
  src/Customer/Admin/CustomerBalanceDetailAdmin.js
  src/Customer/CustomerBalance.js
Labels: enhancement, front-end

#390 issue-353: add password length validation
  src/Customer/CustomerProfileEdit.js
Labels: bug

#384 Issue 369,381,380: Validation for Create/Edit FAQ, Create/Edit Offer [fixed]
  src/Request/Admin/CreateFAQ.js
  src/Request/Admin/EditFAQ.js
  src/VIP/Admin/CreateOffer.js
  src/VIP/Admin/EditOffer.js
Labels: bug, enhancement

#402 Change wait status to await
  src/Appointment/Admin/AppointmentAdmin.js
  src/Appointment/Admin/AppointmentsAdmin.js
Labels: front-end

#410 Clean-up /models and fix typo of terms and conditions
  models/account.js
  models/appointment.js
  models/balance.js
  models/balanceHistory.js
  models/date.js
  models/faqCategory.js
  models/offer.js
  models/requestCategory.js
  models/service.js
  models/staff.js
  models/termsAndConditions.js
  models/time.js
  models/workSchedule.js
  servers/handlers/termsAndConditionsHandler.js
  servers/server.js
Labels: back-end, clean-up, database

#418 Small fixes in request admin
  src/Request/Admin/RequestHomebyAdmin.js
  src/Request/Admin/ViewRequestDetails.js
Labels: bug, front-end

#420 Remove "email verfified"
  src/Register/SignupSuccess.js
Labels: bug, front-end

#425 Date Picker added in Schedule
  src/StaffSchedule/CreateSchedule.js
  src/StaffSchedule/EditStaffSchedule.js
Labels: enhancement, front-end

#439 Fix issues 437 438 433 432
  models/offer.js
  src/VIP/Admin/CreateOffer.js
  src/VIP/Admin/EditOffer.js
Labels: back-end, bug, database, enhancement, front-end, priority: high

#449 Improve message box
  src/PopUp.js
Labels: enhancement, front-end, nice-to-have

#448 Sort schedules
  src/StaffSchedule/ViewSchedulesList.js
Labels: enhancement, front-end

#445 Fixes issue 444, 436, 435, 434
  servers/handlers/offerHandler.js
  src/Appointment/CreateAppointmentWithOffer.js
Labels: back-end, bug, front-end, priority: high
